# 모델
model_name: "Qwen/Qwen2.5-7B-Instruct"

# 데이터
dataset_path: "train_data_n481/dataset.jsonl" # 데이터셋의 jsonl 위치를 입력
val_ratio: 0.1
data_seed: 42

# QLoRA
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
bnb_4bit_quant_type: "nf4"

# 학습
max_seq_length: 8192
num_train_epochs: 3
max_steps: -1             # -1이면 epoch 기준, 양수면 epoch 무시, weight 업데이트 기준
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
lr_scheduler_type: "cosine"
warmup_ratio: 0.05
max_grad_norm: 1.0
optim: "adamw_torch_fused"
bf16: true
gradient_checkpointing: true

# save
output_dir: "outputs/n481_260316"
save_steps: 50
logging_steps: 5

# validation
eval_steps: 50
eval_samples: 10
eval_seed: 42
eval_max_new_tokens: 512

# wandb
wandb_entity: "oh-my-sLM"    # 팀 이름(고정)
wandb_project: "Qwen2.5-7B-Instruct" # 프로젝트의 이름(고정)
wandb_run_name: "n481_260316" # 내가 설정할 이름
